### ISSUE TITLE
Nginx segfault when FreeWAF installed

### ISSUE THREAD

**Issue by emrahcom** [p0pr0ck5/FreeWAF#24]
Hi Robert,

Sometimes I get segfault messages from Nginx, if FreeWAF is enabled. Related lines from dmesg:

[ 2983.164425] nginx[4298]: segfault at 414cb62a ip 00007ff720df7a5a sp 00007fff7cb96820 error 4
[ 3043.214933] nginx[4126]: segfault at 41a61e22 ip 00007ff720e07a5a sp 00007fff7cb96890 error 4
[ 3103.362729] nginx[4301]: segfault at 424f33da ip 00007ff720e07a5a sp 00007fff7cb96820 error 4

This is a Debian Jessie box with a default kernel from repo:
3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt4-3 (2015-02-03) x86_64

nginx-extras and libluajit-5.1-2 packages from Debian repo:
nginx -V
nginx version: nginx/1.6.2
TLS SNI support enabled
configure arguments: --with-cc-opt='-g -O2 -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2' --with-ld-opt=-Wl,-z,relro --prefix=/usr/share/nginx --conf-path=/etc/nginx/nginx.conf --http-log-path=/var/log/nginx/access.log --error-log-path=/var/log/nginx/error.log --lock-path=/var/lock/nginx.lock --pid-path=/run/nginx.pid --http-client-body-temp-path=/var/lib/nginx/body --http-fastcgi-temp-path=/var/lib/nginx/fastcgi --http-proxy-temp-path=/var/lib/nginx/proxy --http-scgi-temp-path=/var/lib/nginx/scgi --http-uwsgi-temp-path=/var/lib/nginx/uwsgi --with-debug --with-pcre-jit --with-ipv6 --with-http_ssl_module --with-http_stub_status_module --with-http_realip_module --with-http_auth_request_module --with-http_addition_module --with-http_dav_module --with-http_flv_module --with-http_geoip_module --with-http_gzip_static_module --with-http_image_filter_module --with-http_mp4_module --with-http_perl_module --with-http_random_index_module --with-http_secure_link_module --with-http_spdy_module --with-http_sub_module --with-http_xslt_module --with-mail --with-mail_ssl_module --add-module=/tmp/buildd/nginx-1.6.2/debian/modules/headers-more-nginx-module --add-module=/tmp/buildd/nginx-1.6.2/debian/modules/nginx-auth-pam --add-module=/tmp/buildd/nginx-1.6.2/debian/modules/nginx-cache-purge --add-module=/tmp/buildd/nginx-1.6.2/debian/modules/nginx-dav-ext-module --add-module=/tmp/buildd/nginx-1.6.2/debian/modules/nginx-development-kit --add-module=/tmp/buildd/nginx-1.6.2/debian/modules/nginx-echo --add-module=/tmp/buildd/nginx-1.6.2/debian/modules/ngx-fancyindex --add-module=/tmp/buildd/nginx-1.6.2/debian/modules/nginx-http-push --add-module=/tmp/buildd/nginx-1.6.2/debian/modules/nginx-lua --add-module=/tmp/buildd/nginx-1.6.2/debian/modules/nginx-upload-progress --add-module=/tmp/buildd/nginx-1.6.2/debian/modules/nginx-upstream-fair --add-module=/tmp/buildd/nginx-1.6.2/debian/modules/ngx_http_substitutions_filter_module

Backtrace of the core dump:
http://www.emrah.com/files/freewafbt1.txt
http://www.emrah.com/files/freewafbt2.txt
http://www.emrah.com/files/freewafbt3.txt

I have Nginx's debug log too but it's really big and I don't know how to find the related lines.

regards
emrah

**Comment by p0pr0ck5** [comment]
Hi,

This might be an underlying issue with the specific Lua module and Nginx version you're using. I would strongly recommending using the latest stable release of OpenResty, built from source, for this reason. The second and third backtraces indicate an issue in regex matching; this might be a problem because we always specify using JIT-compiled regex patterns (though if your PCRE library doesn't support JIT compilation, this should just skip over, thus I assume it's a problem in the PCRE library you're using).

I created a test branch https://github.com/p0pr0ck5/FreeWAF/tree/hotfix-no_pcre that does not use JIT compilation for regexes; can you try using this and see if you notice a difference? Not using regex pattern caching may result in a performance hit, but seeing that you likely aren't using a JIT-enabled PCRE anyway, it might not make a difference performance-wise. If you're still having trouble, I would strongly recommend replacing your nginx-extras binary for OpenResty, using a JIT-capable PCRE library, as shown in the documentation.

**Comment by emrahcom** [comment]
Hi Robert,

I installed hotfix-no_pcre branch and the segfault issue disappears now. 
I'll take a look at OpenResty but I prefer to use Nginx from the official repo of my distro (Debian) because of the maintainability

Best regards
emrah

**Comment by p0pr0ck5** [comment]
Great, glad the patch is working! Might be an issue with the system libpcre, or the Nginx lua API in the jessie package. I made another change that affects how regexes are handled on the hotfix-no_pcre branch (I added back in regex pattern compilation caching, but not JIT-ing); can you re-test with the latest commit and let me know if you see segfaults again?

**Comment by emrahcom** [comment]
I catched two segfault after the next update (cache enabled, jit disabled).

[17414.909859] traps: nginx[27450] general protection ip:7f891d3efa74 sp:7fff4a13ca80 error:0 in libluajit-5.1.so.2.0.3[7f891d3e0000+6c000]
[18067.898839] traps: nginx[25048] general protection ip:7f891d3efbd1 sp:7fff4a13ca10 error:0 in libluajit-5.1.so.2.0.3[7f891d3e0000+6c000]

core dump:
http://www.emrah.com/files/freewafbt4.txt
http://www.emrah.com/files/freewafbt5.txt

I'm continuing to watch

**Comment by emrahcom** [comment]
Oops, these are not segfault. But I think one of them is related with FreeWAF

**Comment by emrahcom** [comment]
http://www.emrah.com/files/freewafbt6.txt

**Comment by p0pr0ck5** [comment]
Okay, I reverted the second change I made. Now `ngx.re.match` and `ngx.re.find` calls only use the case-insensitive flag. Can you try this out for a bit again and let me know if you still see traps or segfaults?

The underlying issue must be either the version of libpcre (which looks like the system default) or the lua module in your nginx-extras package; I already created a separate bug to allow for an option to disable the default regex flags we've been using so far.

**Comment by emrahcom** [comment]
I didn't apply the last change yet. I see traps sometimes but the segfault is really rare now. This is the only segfault during the last 10 hours:
http://www.emrah.com/files/freewafbt8.txt

I installed FreeWAF (ngx.re.match, cached regex, no jit) to another Debian Jessie box (almost the same configuration and same load/traffic). But FreeWAF run in simulation mode. There is no traps or segfaults. I watched this server more than 14 hours

I'll try the next version now

libpcre is from the official Debian Jessie repo.
Package: libpcre3
Source: pcre3
Version: 2:8.35-3.3
Installed-Size: 672
Maintainer: Mark Baker <mark@mnb.org.uk>
Architecture: amd64

**Comment by p0pr0ck5** [comment]
What are the specific differences in configuration between the new Jessie box and the old one? What happens if you run the new box in active mode, or the old one in simulate mode- any difference?

I may not be able to troubleshoot much further, as the reason I wrote this in Lua is because things like the minutiae of memory management are hard ;) So something like a segfault would seem to point to an instability in the lower middleware of the platform, not the code in FreeWAF; this is why I first suggested re-running using OpenResty, as it always contains the latest Nginx and Lua VM source.

Out of curiosity, do you see any errors in the Nginx error log with the following prefix:

`error in waf.regexmatch:`

**Comment by emrahcom** [comment]
I applied the next commit (opts= 'i') to the both server and I run both in active mode.

Server 2:
Many segfaults, if regex's opts is "oij" and nginx doesn't response
No traps, no segfault and very stable when regex's opts is "i" or "oi"

Server 1:
Many segfaults, if regex's opts is "oij" but nginx responses
Mostly stable but sometimes I see traps and segfault when regex's opts is "i" or "oi"

I think "j" option doesn't work for Nginx from Debian Jessie's repo but 'o' and 'i' flags are OK

After the next commit, I get traps and segfaults from server 1:
http://www.emrah.com/files/freewafbt10.txt
http://www.emrah.com/files/freewafbt11.txt
http://www.emrah.com/files/freewafbt12.txt

But when I look at the error.log, it seems that these are not directly related with FreeWAF. I'll send you the error.log file via email because there are many info about server which I don't want to publish

regards

**Comment by p0pr0ck5** [comment]
Thank you for sending the error log!  I pushed another small change to the hotfix branch you've been working off of, can you test that out? The error log you sent indicates it's not an issue in regex parsing, but elsewhere in an old section of code I've been meaning to remove. Let me know if this solves the issue, and if not, can you send me a debug log (I know they are large, try to find a three or 4 second range where you see a segfault).

**Comment by emrahcom** [comment]
Hi Robert,

After the next commit (remove request_line) I didn't get any traps or segfault. Everything seems OK
I tested more than 15 hours

**Comment by p0pr0ck5** [comment]
Glad to hear that the issue has been resolved! I have removed REQUEST_LINE from the development branch as well, for now, can you continue testing and let me know if you see any more issues?

I have also pushed a new development feature that will allow users to disable the 'o' and 'j' PCRE flags; however, not using these flags could results in _severe_ performance degradation in a high-concurrency environment (see issue #8 for details regarding this). In your case, it may not cause severe performance problems if you do not process more than a few hundred requests per second (though this will vary, depending on hardware). Obviously we favor stability above shaving off a few hundred microseconds of processing time, but this fact should be well noted.

**Comment by emrahcom** [comment]
I'm actively using FreeWAF in two servers now. If I see any issue, I'll report it.

I set the PCRE flags to "oi" and the performance is OK for me. Average ~1000 req/s, no significant performance degradation...  And the stability of FreeWAF with Nginx from the official Debian repo is more important than the performance for me.

Maybe it'll be better to set the flag to "oi", if "disable_pcre_optimization" option is checked. I could not see a problem with "o" flag.

Thanks for this cool project

**Comment by p0pr0ck5** [comment]
So, to wrap up, even if the 'j' flag is specified, if the version of libpcre installed doesn't support JIT compilation, it shouldn't cause a segfault, it just should be ignored and the following will be entered in the debug log:

`2015/03/02 13:48:06 [debug] 31730#0: *1 pcre JIT compiling result: 0`

And based on the documentation, there are no library or version limitations on using compile-once mode, so the presence of either of those flags shouldn't cause stability issues. Not using compile-once mode is the real performance killer, but, we can use 'disable_pcre_optimization' as a starting point for troubleshooting in the future if anyone else runs into issues like this.

I'm wondering how much the presence of the request_line collection was causing problems. If you want to grab the latest development branch commit, that defaults to using 'oij', but no request_line collection, perhaps it will not have stability issues with the Jessie nginx-extras package? I'll try to do some testing later this week, more out of curiosity than anything else. At this point, since you're reporting that it's stable, I'm inclined to close this out. Glad we got everything figured out, and thanks for you interest in the project! Feel free to open a new bug if you have any more questions or feature requests :)
