### ISSUE TITLE
FreeWAF stops to log

### ISSUE THREAD

**Issue by emrahcom** [p0pr0ck5/FreeWAF#33]
I upgraded to the current development branch and FreeWAF stops to log. 

Server1:
Common FreeWAF config in /etc/nginx/conf.d/freewaf.conf:
access_by_lua '
        FreeWAF = require "FreeWAF.fw"
        local fw = FreeWAF:new()
        fw:set_option("mode", "ACTIVE")
        fw:set_option("disable_pcre_optimization", true)
        fw:set_option("score_threshold", 10)

        fw:set_option("event_log_target", "file")
        fw:set_option("event_log_target_path", "/var/log/nginx/freewaf.log")
        fw:set_option("event_log_buffer_size", 8192)
        fw:set_option("event_log_verbosity", 3)

        -- fw:set_option("whitelist", "127.0.0.1")
        -- fw:set_option("ignore_rule", 41014)
        -- fw:set_option("ignore_rule", 41015)

        fw:exec()
';

The log file permission is OK. But there is no log.

Server2:
There are two domains and each one has their own config in server { } block. "access_by_lua" blocks are same except the filename in "event_log_target_path". 

log is OK for one domain but it doesn't work for other. But if I comment the log options for the first domain then the second starts to log.

**Comment by p0pr0ck5** [comment]
This is a known issue (see my notes in issue #9):

"Socket logging is a -little- buggy in that, because lua-resty-logger-socket provides a single, global target server, we allow for multiple configurations to potentially conflict (in such a case, the global socket_logger object would be init'd with the values of whatever location configuration triggered _log_event() first). If multiple locations elect socket logging and are specified identical host/port values, no conflict will arise (the same logic follows for file logging and `event_log_target_path`)."

I will add a note to the documentation for socket/file logging, but for now, we don't support logging to multiple files; each `access_by_lua` block needs to be configured with the same `event_log_target_path`.
