### ISSUE TITLE
about performance of freeWAF

### ISSUE THREAD

**Issue by hy05190134** [p0pr0ck5/FreeWAF#53]
1  Is the spend time you test FreeWAF based on  Logging mode or not ?  that is to say , whether you turn on the debug logging switch?

2  I find that if I turn on the debug logging mode, in my machine, it takes 9-10milliseconds, but 900-1000 microseconds when it turn off.

3  On one request, you have make some cache between rules to reduce exec time.  Can we make some cache between requests to reduce response time?

**Comment by p0pr0ck5** [comment]
1. No, performance testing is not done with debug mode active. See my notes in issue #8 for more details on performance testing and profiling.

2. Yes. Debug logging is very expensive; this is already documented.

3. No, because each request will have different data. There's nothing to cache (that I can think of). Is there a specific use case you can point at that we could potentially investigate?

**Comment by hy05190134** [comment]
why some flame graph can't be visted?

**Comment by p0pr0ck5** [comment]
Please provide specific examples. I am able to load them all.

**Comment by p0pr0ck5** [comment]
Closing this after no response and no apparent issue.
