### ISSUE TITLE
uri  equal  "/wp-login.php" 

### ISSUE THREAD

**Issue by hy05190134** [p0pr0ck5/FreeWAF#66]
this is wordpress rules but mod security say that "uri  contain  /wp-login.php" etc, so I think you should not use equal operator.

**Comment by p0pr0ck5** [comment]
No. String equality is less expansive than a regex search, when we're looking for something distinct like a string. This suggestion is entirely wrong.

**Comment by hy05190134** [comment]
@p0pr0ck5  maybe you misunderstand my suggestion, I mean if some uri like '/xxxx/wp-login.php', it will not take action for the rule,

**Comment by p0pr0ck5** [comment]
Hi, sorry, you have a valid point. I won't change any rules in question, because they have a specific target, and they could be changed by end users as needed. The Mod_Security CRS doesn't include any rules that specifically reference wp-login.php, but in the future, we can probably be more less selective.

**Comment by hy05190134** [comment]
@p0pr0ck5  because it belongs to wordpress application, so we just pick them to be a modules for wp.

**Comment by hy05190134** [comment]
@p0pr0ck5  it has many wordpress rules in slr_rules

**Comment by p0pr0ck5** [comment]
Those are the slr rules. We are not duplicating slr functionality, we are only duplicating the base_rules. Users are free to write additional rules as they choose, that's why this is an open source project.
